// <auto-generated />
using System;
using DinhTienManh_Ontap5.model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DinhTienManh_Ontap5.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250621090835_dinhtienmanh")]
    partial class dinhtienmanh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DinhTienManh_Ontap5.model.TrinhBayBaiHat", b =>
                {
                    b.Property<int>("MaTrinhBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrinhBay"), 1L, 1);

                    b.Property<string>("CaSiTrinhBay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTrinhBay")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBaiHat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("MaTrinhBay");

                    b.ToTable("TrinhBayBaiHats");

                    b.HasData(
                        new
                        {
                            MaTrinhBay = 1,
                            CaSiTrinhBay = "Trung",
                            DiaDiem = "Ha Noi",
                            NgayTrinhBay = new DateTime(2025, 6, 21, 16, 8, 35, 420, DateTimeKind.Local).AddTicks(6585),
                            TenBaiHat = "Thuyen khong ben doi",
                            ThoiLuong = 60
                        },
                        new
                        {
                            MaTrinhBay = 2,
                            CaSiTrinhBay = "Trung",
                            DiaDiem = "Da Nang",
                            NgayTrinhBay = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBaiHat = "Thuyen khong ben doi",
                            ThoiLuong = 60
                        },
                        new
                        {
                            MaTrinhBay = 3,
                            CaSiTrinhBay = "Trung",
                            DiaDiem = "TP HCM",
                            NgayTrinhBay = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBaiHat = "Thuyen khong ben doi",
                            ThoiLuong = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
