// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Web_PhongBan_NhanVien.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250621165320_dinhtienmanh")]
    partial class dinhtienmanh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web_PhongBan_NhanVien.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaPhong");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoTen = "Nguyen Van A",
                            Luong = 15000000m,
                            MaPhong = 1
                        },
                        new
                        {
                            Id = 2,
                            HoTen = "Nguyen Van B",
                            Luong = 25000000m,
                            MaPhong = 2
                        });
                });

            modelBuilder.Entity("Web_PhongBan_NhanVien.Models.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("KinhPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PhongBan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KinhPhi = 5000000m,
                            TenPhong = "Phòng Kế Toán",
                            ViTri = "Tầng 1"
                        },
                        new
                        {
                            Id = 2,
                            KinhPhi = 7000000m,
                            TenPhong = "Phòng Nhân Sự",
                            ViTri = "Tầng 2"
                        },
                        new
                        {
                            Id = 3,
                            KinhPhi = 10000000m,
                            TenPhong = "Phòng IT",
                            ViTri = "Tầng 3"
                        });
                });

            modelBuilder.Entity("Web_PhongBan_NhanVien.Models.NhanVien", b =>
                {
                    b.HasOne("Web_PhongBan_NhanVien.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Web_PhongBan_NhanVien.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
